version: '3.8'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/Denver
      VERSION: docker
    volumes:
      - /opt/plexarr/config/plex:/config
      - /home/neckbeard/media/movies:/movies
      - /home/neckbeard/media/tv:/tv
      - /home/neckbeard/media/music:/music
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/Denver
    ports:
      - '7878:7878'
    volumes:
      - /opt/plexarr/config/radarr:/config
      - /home/neckbeard/media/movies:/movies
      - /home/neckbeard/Downloads:/downloads
    restart: unless-stopped
    networks:
      - plexarr_default
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/Denver
    ports:
      - '8989:8989'
    volumes:
      - /opt/plexarr/config/sonarr:/config
      - /home/neckbeard/media/tv:/tv
      - /home/neckbeard/Downloads:/downloads
    restart: unless-stopped
    networks:
      - plexarr_default
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/Denver
    ports:
      - '8686:8686'
    volumes:
      - /opt/plexarr/config/lidarr:/config
      - /home/neckbeard/media/music:/music
      - /home/neckbeard/Downloads:/downloads
    restart: unless-stopped
    networks:
      - plexarr_default
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/Denver
    ports:
      - '9696:9696'
    volumes:
      - /opt/plexarr/config/prowlarr:/config
    restart: unless-stopped
    networks:
      - plexarr_default
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/Denver
    ports:
      - '5055:5055'
    volumes:
      - /opt/plexarr/config/overseerr:/app/config
    restart: unless-stopped
    networks:
      - plexarr_default
  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/Denver
    ports:
      - '6246:6246'
    volumes:
      - /opt/plexarr/config/maintainerr:/opt/data
    restart: unless-stopped
    networks:
      - plexarr_default
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: America/Denver
    ports:
      - '6789:6789'
    volumes:
      - /opt/plexarr/config/nzbget:/config
      - /home/neckbeard/Downloads:/downloads
    restart: unless-stopped
    networks:
      - plexarr_default
networks:
  plexarr_default:
    external: true
